---
deployment:
  tasks:
    - export DEPLOYPATH=/home/smartmet/SmartMetersWebsiteCode/
    - /bin/cp -Rf dist $DEPLOYPATH
    - /bin/cp -f server.js $DEPLOYPATH
    - /bin/cp -f package.json $DEPLOYPATH