
import { Product, ProductCategory, Discount, Language } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    sku: 'EL-3PH-001',
    name: 'SmartMeter Pro 3-Phase',
    category: ProductCategory.ELECTRIC,
    manufacturer: 'SmartMeter',
    series: 'Trifazat',
    mounting: 'Sina DIN',
    protocol: 'Modbus RTU',
    maxCapacity: 80,
    price: 450,
    currency: 'RON',
    stockStatus: 'in_stock',
    isActive: true,
    image: 'https://picsum.photos/400/400?random=1',
    shortDescription: {
      ro: 'Contor electric trifazat industrial cu precizie clasa B.',
      en: 'Industrial 3-phase electric meter with Class B accuracy.'
    },
    fullDescription: {
      ro: 'Acest contor inteligent trifazat este ideal pentru aplicații industriale și comerciale.',
      en: 'This smart 3-phase meter is ideal for industrial and commercial applications.'
    },
    specs: {
      'Voltaj': '3x230/400V',
      'Frecvență': '50Hz',
      'Precizie': 'Clasa B (1%)',
      'Display': 'LCD Backlit',
      'IP': 'IP50'
    }
  },
  {
    id: '2',
    sku: 'WT-DN20-002',
    name: 'AquaSmart Ultrasonic DN20',
    category: ProductCategory.WATER,
    manufacturer: 'AquaTech',
    series: 'Ultrasonic',
    mounting: 'Flansa',
    protocol: 'M-Bus',
    maxCapacity: 2.5,
    price: 320,
    currency: 'RON',
    stockStatus: 'in_stock',
    isActive: true,
    image: 'https://picsum.photos/400/400?random=2',
    shortDescription: {
      ro: 'Apometru ultrasonic inteligent pentru apă rece.',
      en: 'Smart ultrasonic water meter for cold water.'
    },
    fullDescription: {
      ro: 'Tehnologie ultrasonică pentru o precizie ridicată.',
      en: 'Ultrasonic technology for high accuracy.'
    },
    specs: {
      'Diametru': 'DN20',
      'Temp. Max': '50°C',
      'Presiune': 'PN16',
      'Baterie': '10 ani'
    }
  },
  {
    id: '3',
    sku: 'GS-G4-003',
    name: 'GasFlux G4 Smart',
    category: ProductCategory.GAS,
    manufacturer: 'NoARK',
    series: 'Diaphragm',
    mounting: 'Standard',
    protocol: 'Pulse',
    maxCapacity: 6,
    price: 850,
    currency: 'RON',
    stockStatus: 'on_request',
    isActive: true,
    image: 'https://picsum.photos/400/400?random=3',
    shortDescription: {
      ro: 'Contor de gaz cu diafragmă și modul de comunicație.',
      en: 'Diaphragm gas meter with communication module.'
    },
    fullDescription: {
      ro: 'Contor volumetric de gaz cu corecție de temperatură.',
      en: 'Volumetric gas meter with temperature correction.'
    },
    specs: {
      'Tip': 'G4',
      'Presiune Max': '0.5 bar',
      'Conexiune': '1-1/4"',
      'Carcasa': 'Otel Galvanizat'
    }
  },
  {
    id: '4',
    sku: 'TH-HEAT-004',
    name: 'ThermoCompact Integral',
    category: ProductCategory.THERMAL,
    manufacturer: 'Siemens',
    series: 'Compact',
    mounting: 'Retur',
    protocol: 'M-Bus',
    maxCapacity: 1.5,
    price: 680,
    currency: 'RON',
    stockStatus: 'in_stock',
    isActive: true,
    image: 'https://picsum.photos/400/400?random=4',
    shortDescription: {
      ro: 'Contor de energie termică compact.',
      en: 'Compact thermal energy meter.'
    },
    fullDescription: {
      ro: 'Unitate compactă pentru măsurarea energiei termice.',
      en: 'Compact unit for measuring thermal energy.'
    },
    specs: {
      'Senzori': 'Pt500',
      'Baterie': '10 ani',
      'Display': 'Detasabil'
    }
  }
];

export const DISCOUNTS: Discount[] = [
  { code: 'B2B10', type: 'percent', value: 10 },
  { code: 'WELCOME50', type: 'fixed', value: 50 }
];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  ro: {
    'nav.home': 'Acasă',
    'nav.shop': 'Magazin',
    'nav.about': 'Despre Noi',
    'nav.contact': 'Contact',
    'nav.cart': 'Coș',
    'nav.my_orders': 'Comenzile Mele',
    'hero.title': 'Soluții de Contorizare Inteligentă B2B',
    'hero.subtitle': 'Furnizăm echipamente de măsurare precise pentru electricitate, apă, gaz și energie termică.',
    'hero.cta': 'Vezi Produsele',
    'shop.filters': 'Filtre',
    'shop.category': 'Categorie',
    'shop.manufacturer': 'Producător',
    'shop.protocol': 'Protocol',
    'shop.availability': 'Disponibilitate',
    'shop.all': 'Toate',
    'shop.any': 'Oricare',
    'shop.apply': 'Aplică Filtrele',
    'shop.search': 'Caută produse...',
    'shop.price_asc': 'Preț: Crescător',
    'shop.price_desc': 'Preț: Descrescător',
    'shop.add_to_cart': 'Adaugă în Coș',
    'shop.details': 'Detalii',
    'shop.no_results': 'Nu am găsit produse conform filtrelor selectate.',
    'shop.loading': 'Se încarcă produsele...',
    'product.specs': 'Specificații Tehnice',
    'product.description': 'Descriere',
    'product.datasheet': 'Fișa Tehnică',
    'product.download': 'Descarcă PDF',
    'product.request_docs': 'Solicită Documentație',
    'product.docs_unavailable': 'Documentație Indisponibilă Online',
    'product.docs_request_sub': 'Solicită fișa tehnică direct de la echipa noastră.',
    'product.sku': 'Cod produs',
    'product.category': 'Categorie',
    'product.stock_in': 'În stoc',
    'product.stock_request': 'La comandă',
    'product.out_of_stock': 'Stoc Epuizat',
    'product.unavailable': 'Indisponibil',
    'product.back_to_shop': 'Înapoi la Magazin',
    'cart.title': 'Coșul Tău',
    'cart.empty': 'Coșul este gol.',
    'cart.product': 'Produs',
    'cart.price': 'Preț',
    'cart.quantity': 'Cantitate',
    'cart.total': 'Total',
    'cart.subtotal': 'Subtotal',
    'cart.discount': 'Discount',
    'cart.final_total': 'Total Final',
    'cart.summary': 'Sumar Comandă',
    'cart.vat_included': 'TVA (19% inclus)',
    'cart.checkout': 'Finalizează Comanda',
    'cart.continue': 'Continuă Cumpărăturile',
    'cart.code_placeholder': 'Cod reducere',
    'cart.apply': 'Aplică',
    'cart.remove': 'șterge',
    'checkout.title': 'Finalizare Comandă',
    'checkout.contact': 'Date de Contact',
    'checkout.billing': 'Facturare',
    'checkout.shipping': 'Livrare',
    'checkout.diff_shipping': 'Livrare diferită de facturare',
    'checkout.same_address': 'Livrarea la aceeași adresă',
    'checkout.notes': 'Notițe Comandă',
    'checkout.send': 'Trimite Comanda',
    'checkout.sending': 'Se trimite...',
    'checkout.success_title': 'Comandă Trimisă!',
    'checkout.success_msg': 'Comanda a fost trimisă cu succes. Veți fi contactat în curând pe email pentru confirmare și detalii de plată.',
    'checkout.back_home': 'Înapoi la Acasă',
    'checkout.terms_notice': 'Prin plasarea comenzii, sunteți de acord cu Termenii și Condițiile noastre.',
    'common.email': 'Email',
    'common.name': 'Nume',
    'common.company': 'Companie',
    'common.address': 'Adresă',
    'common.city': 'Oraș',
    'common.postal': 'Cod Poștal',
    'common.country': 'Țară',
    'common.phone': 'Telefon',
    'orders.title': 'Istoric Comenzi',
    'orders.no_orders': 'Nu ai nicio comandă',
    'orders.no_orders_sub': 'Odată ce plasezi o comandă, aceasta va apărea aici.',
    'orders.number': 'Număr Comandă',
    'orders.date': 'Data',
    'orders.status': 'Status',
    'orders.items': 'Articole comandate',
    'footer.rights': 'Toate drepturile rezervate.',
    'footer.terms': 'Termeni și Condiții',
    'footer.privacy': 'Politica de Confidențialitate',
    'footer.links': 'Linkuri Utile',
    'footer.support': 'Suport',
    'contact.title': 'Contact',
    'contact.send': 'Trimite',
    'contact.message': 'Mesaj',
    'contact.office': 'Sediu',
    'contact.success': 'Mesaj Trimis!',
    'contact.success_sub': 'Îți mulțumim. Te vom contacta în curând.',
    'contact.send_another': 'Trimite alt mesaj',
    'status.new': 'Nouă',
    'status.processing': 'În procesare',
    'status.in_delivery': 'În curs de livrare',
    'status.complete': 'Completă',
    'status.cancelled': 'Anulată',
    'home.featured': 'Produse Recomandate',
    'home.see_all': 'Vezi toate',
    'home.badge_b2b': 'Focus B2B',
    'home.badge_b2b_desc': 'Soluții dedicate pentru companii și ingineri.',
    'home.badge_support': 'Suport Tehnic',
    'home.badge_support_desc': 'Consiliere expertă privind integrarea protocoalelor (Modbus, M-Bus).',
    'home.badge_shipping': 'Livrare Rapidă',
    'home.badge_shipping_desc': 'Produsele din stoc se livrează în 24 de ore.',
  },
  en: {
    'nav.home': 'Home',
    'nav.shop': 'Shop',
    'nav.about': 'About Us',
    'nav.contact': 'Contact',
    'nav.cart': 'Cart',
    'nav.my_orders': 'My Orders',
    'hero.title': 'Smart B2B Metering Solutions',
    'hero.subtitle': 'We supply precise measuring equipment for electricity, water, gas, and thermal energy.',
    'hero.cta': 'View Products',
    'shop.filters': 'Filters',
    'shop.category': 'Category',
    'shop.manufacturer': 'Manufacturer',
    'shop.protocol': 'Protocol',
    'shop.availability': 'Availability',
    'shop.all': 'All',
    'shop.any': 'Any',
    'shop.apply': 'Apply Filters',
    'shop.search': 'Search products...',
    'shop.price_asc': 'Price: Low to High',
    'shop.price_desc': 'Price: High to Low',
    'shop.add_to_cart': 'Add to Cart',
    'shop.details': 'Details',
    'shop.no_results': 'No products found matching your criteria.',
    'shop.loading': 'Loading products...',
    'product.specs': 'Technical Specifications',
    'product.description': 'Description',
    'product.datasheet': 'Datasheet',
    'product.download': 'Download PDF',
    'product.request_docs': 'Request Documentation',
    'product.docs_unavailable': 'Documentation Unavailable Online',
    'product.docs_request_sub': 'Request the datasheet directly from our team.',
    'product.sku': 'SKU',
    'product.category': 'Category',
    'product.stock_in': 'In Stock',
    'product.stock_request': 'On Request',
    'product.out_of_stock': 'Out of Stock',
    'product.unavailable': 'Unavailable',
    'product.back_to_shop': 'Back to Shop',
    'cart.title': 'Your Cart',
    'cart.empty': 'Your cart is empty.',
    'cart.product': 'Product',
    'cart.price': 'Price',
    'cart.quantity': 'Quantity',
    'cart.total': 'Total',
    'cart.subtotal': 'Subtotal',
    'cart.discount': 'Discount',
    'cart.final_total': 'Final Total',
    'cart.summary': 'Order Summary',
    'cart.vat_included': 'VAT (19% included)',
    'cart.checkout': 'Checkout',
    'cart.continue': 'Continue Shopping',
    'cart.code_placeholder': 'Discount code',
    'cart.apply': 'Apply',
    'cart.remove': 'remove',
    'checkout.title': 'Checkout',
    'checkout.contact': 'Contact Details',
    'checkout.billing': 'Billing Details',
    'checkout.shipping': 'Shipping Details',
    'checkout.diff_shipping': 'Ship to different address',
    'checkout.same_address': 'Ship to billing address',
    'checkout.notes': 'Order Notes',
    'checkout.send': 'Send Order',
    'checkout.sending': 'Sending...',
    'checkout.success_title': 'Order Sent!',
    'checkout.success_msg': 'Your order has been sent successfully. You will be contacted shortly via email for confirmation and payment details.',
    'checkout.back_home': 'Back to Home',
    'checkout.terms_notice': 'By placing the order, you agree to our Terms and Conditions.',
    'common.email': 'Email',
    'common.name': 'Name',
    'common.company': 'Company',
    'common.address': 'Address',
    'common.city': 'City',
    'common.postal': 'Postal Code',
    'common.country': 'Country',
    'common.phone': 'Phone',
    'orders.title': 'Order History',
    'orders.no_orders': 'No orders found',
    'orders.no_orders_sub': 'Once you place an order, it will appear here.',
    'orders.number': 'Order Number',
    'orders.date': 'Date',
    'orders.status': 'Status',
    'orders.items': 'Ordered Items',
    'footer.rights': 'All rights reserved.',
    'footer.terms': 'Terms & Conditions',
    'footer.privacy': 'Privacy Policy',
    'footer.links': 'Useful Links',
    'footer.support': 'Support',
    'contact.title': 'Contact',
    'contact.send': 'Send',
    'contact.message': 'Message',
    'contact.office': 'Headquarters',
    'contact.success': 'Message Sent!',
    'contact.success_sub': 'Thank you. We will contact you shortly.',
    'contact.send_another': 'Send another message',
    'status.new': 'New',
    'status.processing': 'Processing',
    'status.in_delivery': 'In Delivery',
    'status.complete': 'Complete',
    'status.cancelled': 'Cancelled',
    'home.featured': 'Featured Products',
    'home.see_all': 'See all',
    'home.badge_b2b': 'B2B Focused',
    'home.badge_b2b_desc': 'Dedicated solutions for companies and engineers.',
    'home.badge_support': 'Technical Support',
    'home.badge_support_desc': 'Expert advice on protocol integration (Modbus, M-Bus).',
    'home.badge_shipping': 'Fast Shipping',
    'home.badge_shipping_desc': 'Stock products shipped within 24 hours.',
  }
};
